[versions]
minecraft = "1.20.4"
parchment_minecraft = "1.20.2"
parchment_mappings = "2023.12.10"

neoforge = "20.4.167"

fabric_loader = "0.15.3"
fabric_api = "0.92.0+1.20.4"

mdg = "2.0.0-beta.14"
autoservice = "1.1.1"
nexuspublish = "2.0.0-rc-1"

architectury_loom = "1.4.373"

jetbrains_annotations = "24.1.0"

managedversioning = "1.2.8"
registrationutils = "1.20.2-0.1.2"
enhancedgroovy = "0.2.0"

groovybundler = "2.1.1"
groovyduvet = "3.1.2"
gml = "5.0.0"

jankson = "1.2.3"
nightconfig = "3.6.7"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

groovybundler = { module = "org.groovymc:groovybundler", version.ref = "groovybundler" }
groovyduvet = { module = "org.groovymc.groovyduvet:groovyduvet-core", version.ref = "groovyduvet" }
gml = { module = "org.groovymc.gml:gml-core", version.ref = "gml" }

jankson = { module = "blue.endless:jankson", version.ref = "jankson" }
nightconfig_core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig_toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

enhancedgroovy = { module = "com.matyrobbrt.enhancedgroovy:dsl", version.ref = "enhancedgroovy" }

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
mdg = { id = "org.groovymc.modsdotgroovy", version.ref = "mdg" }
architectury_loom = { id = "dev.architectury.loom", version.ref = "architectury_loom" }
registrationutils = { id = "com.matyrobbrt.mc.registrationutils", version.ref = "registrationutils" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }

