{
    "jobs": {
        "build": {
            "outputs": {
                "version": "${{ steps.record_version_capture_version.outputs.version }}"
            },
            "runs-on": "ubuntu-22.04",
            "permissions": {
                "contents": "write"
            },
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_17_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache@v4"
                },
                {
                    "with": {
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/gradle-build-action@v3"
                },
                {
                    "uses": "fregante/setup-git-user@v2"
                },
                {
                    "name": "Tag Release",
                    "run": "./gradlew tagRelease",
                    "id": "tag_release"
                },
                {
                    "name": "Build",
                    "run": "./gradlew build",
                    "id": "build"
                },
                {
                    "run": "git push && git push --tags"
                },
                {
                    "name": "Record Version",
                    "run": "./gradlew recordVersion",
                    "id": "record_version"
                },
                {
                    "name": "Capture Recorded Version",
                    "run": "echo version=$(cat build/recordVersion.txt) >> \"$GITHUB_OUTPUT\"",
                    "id": "record_version_capture_version"
                }
            ]
        },
        "publish": {
            "needs": [
                "build"
            ],
            "runs-on": "ubuntu-22.04",
            "permissions": {
                "contents": "write"
            },
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_17_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0",
                        "ref": "refs/tags/${{needs.build.outputs.version}}"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache@v4"
                },
                {
                    "with": {
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/gradle-build-action@v3"
                },
                {
                    "name": "Publish",
                    "run": "./gradlew publish closeAndReleaseSonatypeStagingRepository",
                    "id": "publish",
                    "env": {
                        "GPG_SIGNING_KEY": "${{ secrets.GPG_SIGNING_KEY }}",
                        "GPG_KEY_PASSWORD": "${{ secrets.GPG_KEY_PASSWORD }}",
                        "CENTRAL_MAVEN_USER": "${{ secrets.CENTRAL_MAVEN_USER }}",
                        "CENTRAL_MAVEN_PASSWORD": "${{ secrets.CENTRAL_MAVEN_PASSWORD }}"
                    }
                }
            ]
        }
    },
    "name": "Release",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "workflow_dispatch": {
            
        }
    }
}